In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv('diabetes.csv')

In [23]:

data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,72.386719,29.108073,157.003527,32.457464,0.471876,33.240885,0.348958
std,3.369578,31.972618,12.096642,8.791221,88.860914,6.875151,0.331329,11.760232,0.476951
min,0.000000,0.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,25.000000,121.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.000000,130.287879,32.400000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,206.846154,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [17]:
mean_diabetes = data[(data['Insulin'] != 0) & (data['Outcome']==1)]['Insulin'].mean()
data.loc[(data['Insulin']==0) & (data['Outcome']==1),'Insulin'] = mean_diabetes
mean_nondiabetes =  data[(data['Insulin'] != 0) & (data['Outcome']==0)]['Insulin'].mean()
data.loc[(data['Insulin']==0) & (data['Outcome']==0),'Insulin'] = mean_nondiabetes

median_bloodpressure = data[data['BloodPressure']!=0]['BloodPressure'].median()
data.loc[data['BloodPressure']==0,'BloodPressure'] = median_bloodpressure

mean_BMI = data[data['BMI']!=0]['BMI'].mean()
data.loc[data['BMI']==0,'BMI'] = mean_BMI

median_skinthickness = data[data['SkinThickness']!=0]['SkinThickness'].median() 
data.loc[data['SkinThickness']==0,['SkinThickness']] = median_skinthickness

C:\Users\NoteBook\AppData\Local\Temp\ipykernel_18748\515229699.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '206.84615384615384' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[(data['Insulin']==0) & (data['Outcome']==1),'Insulin'] = mean_diabetes

In [18]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,206.846154,33.6,0.627,50,1
1,1,85,66,29,130.287879,26.6,0.351,31,0
2,8,183,64,29,206.846154,23.3,0.672,32,1
3,1,89,66,23,94.000000,28.1,0.167,21,0
4,0,137,40,35,168.000000,43.1,2.288,33,1

In [24]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,72.386719,29.108073,157.003527,32.457464,0.471876,33.240885,0.348958
std,3.369578,31.972618,12.096642,8.791221,88.860914,6.875151,0.331329,11.760232,0.476951
min,0.000000,0.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,25.000000,121.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.000000,130.287879,32.400000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,206.846154,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [21]:
data.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.208615,0.081770,0.093546,0.021565,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.217870,0.182037,0.477276,0.218317,0.137337,0.263514,0.466581
BloodPressure,0.208615,0.217870,1.000000,0.191892,0.096170,0.281319,-0.002378,0.324915,0.165723
SkinThickness,0.081770,0.182037,0.191892,1.000000,0.175564,0.543162,0.102188,0.126107,0.214873
Insulin,0.093546,0.477276,0.096170,0.175564,1.000000,0.230073,0.121716,0.165149,0.410918
BMI,0.021565,0.218317,0.281319,0.543162,0.230073,1.000000,0.153400,0.025519,0.311924
DiabetesPedigreeFunction,-0.033523,0.137337,-0.002378,0.102188,0.121716,0.153400,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.324915,0.126107,0.165149,0.025519,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.165723,0.214873,0.410918,0.311924,0.173844,0.238356,1.000000